INSERT INTO `formas_violencia` (`id_forma`, `nombre_forma`) VALUES
(9, 'Acoso Sexual'),
(2, 'Acoso u Hostigamiento'),
(3, 'Amenazas'),
(11, 'Esclavitud Sexual'),
(15, 'Esterilización Forzada'),
(24, 'Femicidio'),
(25, 'Inducción o Ayuda al Suicidio'),
(7, 'Prostitución Forzada'),
(22, 'Tráfico de Mujeres, niñas y  adolescentes '),
(23, 'Trata de Mujeres, niñas y adolescentes'),
(5, 'Violencia Familiar'),
(4, 'Violencia Física'),
(20, 'Violencia Ginecológica'),
(18, 'Violencia Informática'),
(16, 'Violencia Institucional'),
(13, 'Violencia Laboral'),
(12, 'Violencia Mediática'),
(21, 'Violencia Multicausal'),
(14, 'Violencia Obstétrica'),
(10, 'Violencia Patrimonial y Económica'),
(19, 'Violencia Política'),
(1, 'Violencia Psicológica'),
(6, 'Violencia Sexual '),
(8, 'Violencia Sexual en Pareja'),
(17, 'Violencia Simbólica');