INSERT INTO `organismo` (`id`, `nombre_organismo`, `status`) VALUES
(1, 'Físcalia', 1),
(2, 'Polícia', 1),
(3, 'Defensa Pública', 1),
(4, 'Consejo de Protección del niño', 1),
(5, 'Defensoría NNA', 1),
(6, 'CICPC', 1),
(7, 'Inspectoría del Trabajo', 1),
(8, 'INPSASEL', 1),
(9, 'Clínica Juridica', 1),
(10, 'Defensoria del Pueblo', 1),
(11, 'Superintendencia Nacional Arrendamientos', 1),
(12, 'Sindicatura Municipal', 1),
(13, 'IAGESAN', 1),
(14, 'Psicologa de IAMMUJER Lcda. Claudia Pereira', 1),
(15, 'CESADE PSICOLOGIA', 1),
(16, 'SEPNA', 1),
(17, 'SIPEL', 1),
(18, 'LOPNNA', 1);
